# Generated by Django 4.2.13 on 2024-06-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_image',
        ),
    ]
