# Generated by Django 4.2.13 on 2024-06-26 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_studentchapterquizattended_blocked'),
        ('users', '0007_alter_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='api.program'),
        ),
    ]
