# Generated by Django 4.2.13 on 2024-06-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_subjectnotes_subjectreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapteritem',
            name='video',
            field=models.FileField(default='https://www.youtube.com/watch?v=SqcY0GlETPk', upload_to='path-to-upload'),
        ),
    ]
