# Generated by Django 4.2.13 on 2024-06-14 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_name_alter_user_username'),
        ('api', '0007_alter_chapteritem_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentChapterQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('chapterquiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chapterquiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentChapterQuizProgressPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.SmallIntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chapter')),
                ('chapterquiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chapterquiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.RemoveField(
            model_name='chapterquizanswer',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='chapterquizanswer',
            name='student',
        ),
        migrations.DeleteModel(
            name='SubjectReview',
        ),
        migrations.DeleteModel(
            name='ChapterQuizAnswer',
        ),
    ]
