# Generated by Django 4.2.13 on 2024-06-18 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_studentchapterquizanswer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentchapterquizprogresspercent',
            name='chapterquiz',
        ),
    ]
