# Generated by Django 4.2.13 on 2024-06-18 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_studentchapterquizprogresspercent_chapterquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchapterquizanswer',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.chapter'),
            preserve_default=False,
        ),
    ]
