# Generated by Django 4.2.13 on 2024-06-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_subjectnotes_subject_subjectquestion_questionanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectquestion',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
