# Generated by Django 4.2.13 on 2024-06-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_user_image'),
        ('api', '0012_subjectquestion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswers',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
            preserve_default=False,
        ),
    ]
