# Generated by Django 4.2.13 on 2024-06-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_questionanswers_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswers',
            name='student',
        ),
    ]
