# Generated by Django 4.2.13 on 2024-06-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_studentchapterquizattended'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchapterquizattended',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
